### ISSUE TITLE
Error: The "path" argument must be of type string. Received type undefined

### ISSUE THREAD

**Issue by gracegotlost** [pedronauck/gatsby-starter-docz#7]
On my first run `gatsby develop` it threw an error: `Error: Cannot find module 'to-style'`, I followed [this](https://github.com/doczjs/gatsby-starter-docz/issues/4 ) approach and then it threw an GraphQL error: `Multiple "root" queries found: "DefaultSEOQuery" and "DefaultSEOQuery".
Only the first ("DefaultSEOQuery") will be registered.`. Following [this](https://github.com/doczjs/gatsby-starter-docz/issues/3) approach I upgraded my `gatsby-theme-docz` to `gatsby-theme-docz@next`. And now it threw another error below that I wasn't able to solve yet. 

```
$ gatsby develop
warn Configuring yargs through package.json is deprecated and will be removed in
⠙ open and validate gatsby-configs

 ERROR

UNHANDLED REJECTION The "path" argument must be of type string. Received type undefined



  Error: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type s  tring. Received type undefined

  - validators.js:112 validateString
    internal/validators.js:112:11

  - gatsby-config.js:58 module.exports
    [coolest-library]/[gatsby-theme-docz]/gatsby-config.js:58:22

  - index.js:73 resolveTheme
    [coolest-library]/[gatsby]/dist/bootstrap/load-themes/index.js:73:19

  - index.js:138
    [coolest-library]/[gatsby]/dist/bootstrap/load-themes/index.js:138:22

⠙ open and validate gatsby-configs
```

Anyone has any suggestions? Huge thanks!

**Comment by kissu** [comment]
Thanks to [this video](https://egghead.io/lessons/gatsby-add-documentation-to-a-gatsby-site-with-the-docz-gatsby-theme), I found that it's working with the version `^2.0.0-rc.1` of the package. :ok_hand:
